# This is a basic workflow to help you get started with Actions

name: AutoBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install pyinstaller
        run: pip3 install pyinstaller

      - name: Build app
        run: |
          pyi-makespec -F -w --osx-bundle-identifier "ga.swjtu.calendar"  -n "SWJTU 日历" -i assets/imgs/logo.ico main.py
          pyinstaller --clean -y "SWJTU 日历.spec"
        

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: false
          title: "Latest auto Build"
          files: |
            **/dist/*.exe
